[package]
name = "conu-relay"
version = "0.1.11"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "conu-relay"
path = "src/main.rs"

[dependencies]
conu-core.workspace = true
conu-protocol.workspace = true
rand_core = { version = "0.6", features = ["getrandom"] }
sha2 = "0.10"

[lints]
workspace = true
