[package]
name = "conu-cli"
version = "0.1.3"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "conu"
path = "src/main.rs"

[dependencies]
conu-core.workspace = true
conu-protocol.workspace = true
crossterm = "0.28"
native-tls = "=0.2.14"
serde = "1"
serde_json = "1"
sha2 = "0.10"
flate2 = "1"
tar = "0.4"
zip = { version = "6", default-features = false, features = ["deflate"] }

[lib]
name = "conu_cli"
path = "src/lib.rs"

[lints]
workspace = true
