[package]
name = "conu-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "conu"
path = "src/main.rs"

[dependencies]
conu-core.workspace = true
conu-protocol.workspace = true
serde_json = "1"
sha2 = "0.10"

[lib]
name = "conu_cli"
path = "src/lib.rs"

[lints]
workspace = true
